Feature/category
mash-up-kr/proof_web pull request #54
Opened 2022-08-16 12:46 UTC by zi-gae

## Feature
- 혼술 및 단체 술 선택지 페이지 추가 
- 우측에 화살표가 있는 카드 컴포넌트 추가
- 버튼 액티브 상태 일 때 기본 값 추가
- 백그라운드 색상 기본 값 추가

## Refactor

- 디자인시스템 `Button` 컴포넌트 `fullWidth` 의도를 명확히 하도록 변경
- `Button` 컴포넌트의 width 값과 fullWidth 값 xor 관계 타입으로 변경

## Description

술드컵 상황선택은 쿼리파라미터로 값을 구분 짓도록 했습니다.  eg) `category/alone`, `category/group` 

## TODOS

- Text 컴포넌트가 type 에 따라 시멘틱한 태그로 사용 될 수 있도록 해야함
- Text 컴포넌트의 color props 타입을 선언적으로 변경
- Header 컴포넌트 좌우 여백 값 수정
- Title 컴포넌트 topQuestion, bottomQuestion props 하나로 변경 후 뉴라인 및 line-height 값으로 대응
- 디자인시스템 Button 컴포넌트에 선언된 XOR, Without 타입 유틸리티로 분리
- https://github.com/mash-up-kr/proof_web/pull/52 에서 추가 된 카드 공통화
- 이미지 레이지로딩

##  Screenshot
### IPhoneSE

<img width="374" alt="image" src="https://user-images.githubusercontent.com/39829378/184880115-f94c0b62-1b0d-411a-8201-3d9de56bd515.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/39829378/184880171-7616c624-b933-415a-a30b-bf18c2695975.png">

##  Note
작업이 많이 늦었네여. 같이 챙겨 가면 좋을 것 같은 TODOS 몇개 작성했슴다. 프로젝트 꼭 성공하자. 파이팅 파이팅!! 👊🏻

2022-08-17 17:52 UTC, otterji approved these changes
고생하셨습니다

2022-08-17 17:53 UTC, zi-gae commented on apps/service/src/pages/category/[with].tsx
> +  console.log(params?.with);
써제션 감사함다

2022-08-18 03:34 UTC, poiu694 approved these changes
코드 많이 배웠습니다......

TODO 남겨주신 부분들은 열심히 작업해보겠습니당 :) 감사합니다 !!!~

2022-08-18 15:27 UTC, huewilliams requested changes
작업 수고하셨습니다!
시멘틱 태그랑 Type Util 만들어서 활용한 부분에서 많이 배웠습니다!
자잘한 부분들만 수정 부탁드립니당

2022-08-18 15:27 UTC, huewilliams commented on apps/service/src/components/WithCard.tsx
> +  padding: ${({ theme }) => theme.padding.lg};
lg가 number 20으로 정의되어 있어서 뒤에 px이 필요할 것 같습니다

2022-08-19 02:18 UTC, zi-gae commented on apps/service/src/components/WithCard.tsx
> +  "https://user-images.githubusercontent.com/39829378/184810860-51607da1-b60b-41de-8ca2-135e65b223b4.svg";
다이나믹UI로 동작한다 가정하고 개발했슴당. (백엔드에서 다 내려 달라 했던 기억이..?)

2022-08-19 02:18 UTC, zi-gae commented on apps/service/src/pages/category/index.tsx
> +import { useRouter } from "next/router";
https://github.com/mash-up-kr/proof_web/pull/54/commits/6ac18626e61ea70b117c1eadada6ffcd5e3fcc36 반영했슴당

2022-08-19 02:18 UTC, zi-gae commented on apps/service/src/pages/category/index.tsx
> +const ARROW_URL =
https://github.com/mash-up-kr/proof_web/pull/54/commits/6ac18626e61ea70b117c1eadada6ffcd5e3fcc36 슥슥

2022-08-19 02:18 UTC, zi-gae commented on apps/service/src/pages/category/index.tsx
> +  margin-top: 10vh;
https://github.com/mash-up-kr/proof_web/pull/54/commits/3d7f1f5af578ac98c8337d36704bfd7060a109e1 슥삭쇽

2022-08-19 02:50 UTC, zi-gae commented on apps/service/src/components/ContentCard.tsx
> +      <Text color="#C4BEFF" type="body5">
https://github.com/mash-up-kr/proof_web/pull/54/commits/956d9241976dce0d747ef4206c1ad8aeaa14f69b 넴

2022-08-19 02:50 UTC, zi-gae commented on apps/service/src/components/WithCard.tsx
> +  padding: ${({ theme }) => theme.padding.lg};
https://github.com/mash-up-kr/proof_web/pull/54/commits/956d9241976dce0d747ef4206c1ad8aeaa14f69b 슥삭

2022-08-19 02:50 UTC, zi-gae commented on apps/service/src/components/WithCard.tsx
> +const ARROW_URL =
https://github.com/mash-up-kr/proof_web/pull/54/commits/956d9241976dce0d747ef4206c1ad8aeaa14f69b

2022-08-19 15:14 UTC, huewilliams approved these changes

2022-08-19 20:31 UTC, otterji commented
머지할게요

2022-08-19 20:32 UTC, merged