Feature/result share
mash-up-kr/proof_web pull request #59
Opened 2022-08-20 12:22 UTC by otterji

## Root Cause
- 공유하기 기능 테스트용 PR 입니당

2022-08-23 13:19 UTC, poiu694 approved these changes
고생하셨습니다!

2022-08-23 13:19 UTC, poiu694 commented on apps/service/src/hooks/useUserAgent.ts
> +type IUseUserAgentReturn = Omit<UAParser.IResult, "ua">;
굳이 싶긴 하지만 저도 최근에 알게 되었는데

https://github.com/microsoft/TypeScript/wiki/Coding-guidelines#names

타입스크립트 코딩 가이드라인에서 네이밍 규칙 2번 보면 I로 타입 시작하지 않는걸 권장하더라고요!

인사이트 공유차원에서 코멘트남깁니당!

2022-08-23 13:32 UTC, otterji commented
> 고생하셨습니다!

앗 아직 완성 아닌데 ㅎ 작업 마무리하고 다시 리뷰요청 드리겠습니당 ^^77

2022-08-23 13:32 UTC, otterji commented on apps/service/src/hooks/useUserAgent.ts
> +type IUseUserAgentReturn = Omit<UAParser.IResult, "ua">;
호오 감사합니다!

2022-08-23 13:33 UTC, poiu694 commented
> _앗 아직 완성 아닌데 ㅎ 작업 마무리하고 다시 리뷰요청 드리겠습니당 ^^77_

ㅎㅎ...빨리해버린거 들켰따

2022-08-26 14:38 UTC, zi-gae reviewed
🙇🏻‍♂️

2022-08-26 14:38 UTC, zi-gae commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
훅이 아닌데 use 네이밍 사용한 이유가 있을까유? (궁금)

2022-08-26 14:44 UTC, zi-gae commented on apps/service/src/hooks/useUserAgent/helpers.ts
> +  const ua: UserAgent = Object.freeze({
최근 ts 에서는 Object.freeze 안쓰는 추세이고 리터럴 타입으로 관리 가능한 as const 로 많이써유.

2022-08-26 14:58 UTC, otterji commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
안그래도 유틸 함수로 만드는 것이 맞나 고민돼서 처음엔 일반 함수로 만들었다가, 확장성을 생각해 훅으로 만들었습니다.

현재 저희 서비스에서는 안드로이드 앱 내의 웹 뷰인지만 알면 되기 때문에 간단한 함수만 필요로 하지만, 추후에 각각의 다양한 환경에 따른 컴포넌트를 반환해야 한다든지(컴포넌트 래핑), 이를 통해 복잡한 로직이 따로 추가된다든지 하는 상황이 발생할 때 해당 로직을 추가하기 편리하지 않을까 생각했습니다.

다른 더 좋은 방향이 있을까요?

2022-08-26 15:39 UTC, otterji commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
@zi-gae 
오신 김에 의견 하나 여쭈어봐도 될까요?

현재 결과 페이지에서 공유하기 버튼 클릭하면 결과 페이지 링크가 다른 사람들에게 공유되는 작업을 진행중입니다.

공유 된 페이지인지 아닌지에 따라 UI가 달라서 분기처리를 하려하는데 어떠한 방법을 사용할 지 고민되네요.
아래 방법에 대한 의견이나, 다른 추천해주실만한 방법이 있을까요?

1. URL 쿼리 파라미터 사용
=> result/1?shared=true 
=> 가장 쉽고 간단하며 생각해야할 경우가 적지만, url에 노골적으로 드러나서 싫음

2. 클라이언트 상태 사용
=> RecoilState에 값이 있으면 내가 직접 한 술드컵 결과이고, 없으면 공유 받은 사람으로 간주
=> 새로고침하면 날라감..

3. 세션 스토리지 사용 (referrer)
=> next에는 referrer 사용 못해서 세션 스토리지에 이전 path를 저장
=> 전체 페이지에 적용해야하는가? 이 분기 하나를 위해 공수가 큰 것 아닐까?

4. 미들웨어에서 응답 헤더에 담기
=> 내가 직접 진행한 월드컵에서 넘어갈때 미들웨어에 요청 헤더에 분기를 넣어줌
=> 이 또한 새로고침하면 날라가지 않나?

2022-08-26 16:12 UTC, otterji commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
생각해보니 결국 내 순위표가 나오려면 월드컵 결과 데이터가 다 따로 저장되어야 하네요..
어차피 분기처리 해줘야하니 1번으로 하고, shared말고 노골적으로 드러나지 않는 쿼리 파람을 고민해보겠습니다~

2022-08-27 14:54 UTC, huewilliams requested changes
작업 수고하셨습니다!
user-agent 다루는 부분에서 많이 배웠습니다. 혹시 user-agent 작업하시면서 참고하신 레퍼런스 있으시면 공유해주시면 많이 도움이 될 것 같습니당 ㅎㅎ

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/hooks/useUserAgent/helpers.ts
> +  const result: UAParser.IResult = new UAParser(
![image](https://user-images.githubusercontent.com/37013834/187034660-7bb040f5-66fb-4876-b6ad-86098e9aba9b.png)

android 환경에서도 `navigator.userAgent`로 유저 에이전트 정보를 가져올 수 있는 걸로 아는데 문자열로 직접 넣어주신 이유가 있을까요?

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/pages/result/[drinkId].tsx
> +            categoryName: DRINK_CARDS[1].category.name,
Drink 인터페이스의 category 구조가 바뀌어서 수정했습니다! [8cdf230](https://github.com/mash-up-kr/proof_web/pull/59/commits/8cdf230b0887675bfe3fa995b9293dd1bab5a6c1)

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/components/InstallAppBottomSheet.tsx
> +      headerProps={{
BottomSheet 컴포넌트 내에서 headerProps를 옵셔널 하게 바꾸는게 좋아 보이네용

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/components/InstallAppBottomSheet.tsx
> +      fullHeight={false}
fullHeight는 옵셔널 필드라서 false라면 넘기지 않아도 될 것 같습니다!

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/pages/result/[drinkId].tsx
> +  const [isDrinkDetailBottomSheetOpened, setIsDrinkDetailBottomSheetOpened] =
마이너한 부분이긴 한데, hook 종류 별로 정렬되면 좋을 것 같네요. isInstallAppBottomSheetOpened랑 isDrinkDetailBottomSheetOpened가 같이 있게 하는 등

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/pages/result/[drinkId].tsx
> +  const dataToShare = {
여기도 dom 내장 ShareData로 타입 지정해서 사용하면 좋을 것 같네요

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/pages/result/[drinkId].tsx
> +    if (result === "copiedToClipboard") {
result를 string이 아니라 enum으로 관리하는 건 어떨까요? (휴먼 에러 방지)

2022-08-27 14:54 UTC, huewilliams commented on apps/service/src/pages/result/[drinkId].tsx
> +          drinkName={DRINK_CARDS[1].name}
DrinkInfoBottomSheet로 전달되는 데이터가 DRINK_CARDS[1]로 고정되어 있어서 winnerDrink 데이터를 넘기도록 수정했습니당
[9807622](https://github.com/mash-up-kr/proof_web/pull/59/commits/98076221a2f97dc25b78d3a2b009326264a5934c)

2022-08-29 07:51 UTC, otterji commented on apps/service/src/pages/result/[drinkId].tsx
> +    if (result === "copiedToClipboard") {
현재 타입이 string이 아니고 요렇게 지정해줬는데,
`new Promise<"shared" | "copiedToClipboard" | "failed">`
따로 enum으로 관리하자는 말씀이실까욤??

2022-08-29 08:07 UTC, otterji commented on apps/service/src/components/InstallAppBottomSheet.tsx
> +      fullHeight={false}
fullHeight 디폴트 값이 true라서 입력해주었는데, 어떤 방향으로 바꿀 수 있을까요?

2022-08-29 08:08 UTC, otterji commented on packages/design-system/components/bottomSheet/BottomSheet.tsx
> +      <BottomSheetContent>{props.children}</BottomSheetContent>
죠습니당 반영했습니당 57eedf91da72ab6d6dab4418921d7e4c8fec490a

2022-08-29 08:08 UTC, otterji commented on apps/service/src/utils/share.ts
> +type Data = {
굿굿 57eedf91da72ab6d6dab4418921d7e4c8fec490a

2022-08-29 08:09 UTC, otterji commented on apps/service/src/hooks/useUserAgent/helpers.ts
> +  const result: UAParser.IResult = new UAParser(
훅에선 파싱 자체만 하고 제어권은 따로 가져가고 싶었는데, 굳이 그럴 필요 없을 것 같네요! 전체적으로 수정했습니당 57eedf91da72ab6d6dab4418921d7e4c8fec490a

2022-08-29 08:10 UTC, otterji commented on apps/service/src/components/InstallAppBottomSheet.tsx
> +      headerProps={{
아주 좋네용 ff1aa5ded1fd9090aaacb58bb76ddb69e07dfeb0

2022-08-29 08:11 UTC, otterji commented on apps/service/src/pages/result/[drinkId].tsx
> +  const [isDrinkDetailBottomSheetOpened, setIsDrinkDetailBottomSheetOpened] =
정리 함 했습니당! 정말 보기 불편했었네요 3589f12ada9d123af6f07779b177ee785e88a402

2022-08-29 08:11 UTC, otterji commented on apps/service/src/pages/result/[drinkId].tsx
> +  const dataToShare = {
ㅉㅑ쟌 8847eaa5edc504479c2c37e896a6572423e8a5b2

2022-08-29 08:28 UTC, zi-gae commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
> 안그래도 유틸 함수로 만드는 것이 맞나 고민돼서 처음엔 일반 함수로 만들었다가, 확장성을 생각해 훅으로 만들었습니다.
> 
> 현재 저희 서비스에서는 안드로이드 앱 내의 웹 뷰인지만 알면 되기 때문에 간단한 함수만 필요로 하지만, 추후에 각각의 다양한 환경에 따른 컴포넌트를 반환해야 한다든지(컴포넌트 래핑), 이를 통해 복잡한 로직이 따로 추가된다든지 하는 상황이 발생할 때 해당 로직을 추가하기 편리하지 않을까 생각했습니다.
> 
> 다른 더 좋은 방향이 있을까요?

유틸이 훅으로 확장될 것을 고려해서 훅으로 만들었다는 말씀 맞을까요? 맞는다면 유틸로 분리하시고 훅으로 확장될 필요가 있다면 훅에서 유틸을 임포트 해서 사용하도록 해야 합니다. 

- 추상화의 의도가 구현과 다름
- "확장성을 고려하여 훅이 아니지만 훅으로 만듦"이라는 정보를 알아야하기에 인지 부하가 걸림
- 확장이 되지 않는다면 잘못된 설계로 이어짐

2022-08-29 08:33 UTC, zi-gae commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
> 생각해보니 결국 내 순위표가 나오려면 월드컵 결과 데이터가 다 따로 저장되어야 하네요.. 어차피 분기처리 해줘야하니 1번으로 하고, shared말고 노골적으로 드러나지 않는 쿼리 파람을 고민해보겠습니다~

옳바른 uri 설계를 위해서 쿼리스트링은 UI 컴포넌트 변경에 개입하면 안됩니다. 아래와 같이 패스에 포함시키는게 맞을 것 같아요

eg) 
DOMAIN/result/shared

2022-08-29 11:43 UTC, otterji commented on apps/service/src/hooks/useUserAgent/useUserAgent.ts
> +export function useUserAgent() {
감사해요
- useUserAgent 수정: d540f09cc91e3ace268481cce25f6069e7750fe4
- uri 수정: 393fc79c1a058e485371eb248cd033cd025355d3

2022-08-29 11:55 UTC, otterji commented on apps/service/src/hooks/useUserAgent/helpers.ts
> +  const ua: UserAgent = Object.freeze({
d540f09cc91e3ace268481cce25f6069e7750fe4 감사합니다

2022-08-29 11:58 UTC, otterji commented on apps/service/src/hooks/useUserAgent/helpers.ts
> +  const result: UAParser.IResult = new UAParser(
최종적으로 파싱 관련 로직을 유틸 함수로 분리하고, 훅에서 `navigator.userAgent` 제어하게끔 수정했습니다!
d540f09cc91e3ace268481cce25f6069e7750fe4

2022-08-30 06:51 UTC, otterji reviewed
자코자리 🙄
(자기 코드 자기가 리뷰한다는 뜻ㅎ)

2022-08-30 06:51 UTC, otterji commented on apps/service/src/utils/index.ts
> +export * from "./parseUserAgent";
```suggestion
export * from "./parseUserAgent";
export * from "./getRankingRounds";
```

2022-08-30 06:51 UTC, otterji commented on apps/service/src/utils/getRankingRounds.ts
> +  const maxIndexArray = [...Array(maxIndex)].map((v, i) => Math.pow(2, i));
```suggestion
  const maxIndexArray = Array.from({ length: maxIndex }, (_, i) => 2 ** i);
```

2022-08-30 06:51 UTC, otterji commented on apps/service/src/utils/getRankingRounds.ts
> +  const maxIndexArray = [...Array(maxIndex)].map((v, i) => Math.pow(2, i));
```suggestion
  const maxIndexArray = [...Array(maxIndex)].map((_, i) => 2 ** i);
```

중요한 부분은 아니지만,, 의견이 궁금해서 여쭈어봅니당

위 써제션과 아래 써제션중에 뭐가 더 깔끔해보이시나요?

그리고 Array 생성자에 new를 붙이시는 편이신가요?
Array() 는 암묵적으로 new 를 붙여주는걸로 알고 있는데, 명시해주는게 좋을까요?

전 아래 코드가 더 직관적이란 생각이 드는데.. 혹시 더 생각해보면 좋을 부분이 있을까요?

2022-08-30 06:51 UTC, otterji commented on apps/service/src/components/Rankings.tsx
> +    margin-right: 24px;
[first-child 와 first-of-type 차이점 참고](https://www.geeksforgeeks.org/difference-between-first-child-and-first-of-type-selector-in-css/#:~:text=The%20%3Afirst%2Dchild%3A%20The,every%20element%20of%20it's%20parent.)

2022-08-30 07:25 UTC, poiu694 commented on apps/service/src/utils/getRankingRounds.ts
> +  const maxIndexArray = [...Array(maxIndex)].map((v, i) => Math.pow(2, i));
성능상 유의미한 차이가 아니라, 개인적인 취향들로 갈릴 것 같은데

저는 Array from 으로 하는 편입니당! 그 이유는 한글로 해석하면서 읽을 때 개인적으로 편하더라고요!

Array.from => 새로운 배열을 무엇으로부터 만든다

[...Array()] 어떤 새로운 배열을 만들고 spread 한 뒤, 특정 작업을 한다

이렇게 해석을 하는데, 전자가 남의 코드를 읽을 때 해석이 잘 되는 것 같은 기분탓이 있어서 전자로 사용합니당

2022-08-30 07:26 UTC, poiu694 commented on apps/service/src/utils/getRankingRounds.ts
> +  const maxIndexArray = [...Array(maxIndex)].map((v, i) => Math.pow(2, i));
Math.pow와 ** 연산자도 비슷한 이유로 전자로 사용하는데

** 을 잘 보면 좋겠지만, 피곤하면 * 로 해석할 수도 있을 것 같아서

좀 더 의미 전달 차원에서 Math.pow로 사용하는 것 같아요!

2022-08-30 07:28 UTC, poiu694 commented on apps/service/src/utils/getRankingRounds.ts
> +  const maxIndexArray = [...Array(maxIndex)].map((v, i) => Math.pow(2, i));
new를 붙이는 경우와 안 붙이는 경우를 저는

new 키워드는 기존 변수로부터 만드는게 아니라, 새로 무언가를 만들 때 사용하고,

new를 쓰지 않는 경우는 기존 변수를 형변환을 이용하려 할 때 사용하는 것 같아요!

2022-08-30 07:37 UTC, otterji commented on apps/service/src/utils/getRankingRounds.ts
> +  const maxIndexArray = [...Array(maxIndex)].map((v, i) => Math.pow(2, i));
@poiu694 호오 그렇게 생각할 수도 있겠네요! 자세한 의견 너무 감사합니다..!! 🥺 갬동

2022-08-30 07:46 UTC, poiu694 approved these changes
스윽하러 왔습니다!!! 고생하셨습니당 ㅎㅅㅎ

2022-08-30 07:46 UTC, poiu694 commented on apps/service/src/pages/result/[mode]/[drinkId].tsx
> +    url: `${BASE_URL}${router.pathname}?shared=true`,
요기 shared에서 바뀐 라우팅 적용해야 할 걋 같아요!

2022-08-30 08:04 UTC, otterji commented on apps/service/src/pages/result/[mode]/[drinkId].tsx
> +    url: `${BASE_URL}${router.pathname}?shared=true`,
헉 세상에 감사합니다 🥹 큰일날뻔 ea8e0061d5361d859f9d29f7f0050a491d58ac04

2022-08-31 08:13 UTC, huewilliams approved these changes

2022-08-31 08:37 UTC, merged